//전체 도서
export const GET_ALL_BOOKS_REQUEST = 'GET_ALL_BOOKS_REQUEST';
export const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_BOOKS_SUCCESS';
export const GET_ALL_BOOKS_FAILURE = 'GET_ALL_BOOKS_FAILURE';

//도서 디테일
export const GET_BOOK_REQUEST = 'GET_BOOK_REQUEST';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAILURE = 'GET_BOOK_FAILURE';

//베스트셀러
export const GET_BESTSELLER_BOOKS_REQUEST = 'GET_BESTSELLER_BOOKS_REQUEST';
export const GET_BESTSELLER_BOOKS_SUCCESS = 'GET_BESTSELLER_BOOKS_SUCCESS';
export const GET_BESTSELLER_BOOKS_FAILURE = 'GET_BESTSELLER_BOOKS_FAILURE';
export const RESET_BOOKS = 'RESET_BOOKS';
