//add review
export const ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAILURE = 'ADD_REVIEW_FAILURE';

export const GET_ALL_REVIEWS_OF_BOOK_REQUEST = 'GET_ALL_REVIEWS_OF_BOOK_REQUEST';
export const GET_ALL_REVIEWS_OF_BOOK_SUCCESS = 'GET_ALL_REVIEWS_OF_BOOK_SUCCESS';
export const GET_ALL_REVIEWS_OF_BOOK_FAILURE = 'GET_ALL_REVIEWS_OF_BOOK_FAILURE';
