// import './styles/styles.css';
'use client';
import { useEffect } from 'react';

import Tree from 'rc-tree';
import 'rc-tree/assets/index.css';

import { useDispatch, useSelector } from 'react-redux';

import { getAllCategoriesRequest } from './actions/types';
import { RootState } from './reducers';
import { AppDispatch } from './store/store';
import { Category } from './models/category';

export default function Home() {
  const { categories } = useSelector((store: RootState) => store.category);
  const dispatch = useDispatch<AppDispatch>();

  useEffect(() => {
    dispatch(getAllCategoriesRequest());
  }, []);

  const categoryData = [
    {
      id: '1',
      name: '소설/시/희곡',
      parent_id: '0',
      level: 2,
      route: '국내도서>소설/시/희곡',
      children: [
        {
          id: '50930',
          name: '과학소설(SF)',
          parent_id: '1',
          level: 3,
          route: '국내도서>소설/시/희곡>과학소설(SF)',
          children: [
            {
              id: '89481',
              name: '외국 과학소설',
              parent_id: '50930',
              level: 4,
              route: '국내도서>소설/시/희곡>과학소설(SF)>외국 과학소설',
              children: [],
            },
            {
              id: '89482',
              name: '한국 과학소설',
              parent_id: '50930',
              level: 4,
              route: '국내도서>소설/시/희곡>과학소설(SF)>한국 과학소설',
              children: [],
            },
          ],
        },
        {
          id: '50922',
          name: '독일소설',
          parent_id: '1',
          level: 3,
          route: '국내도서>소설/시/희곡>독일소설',
          children: [],
        },
        {
          id: '50927',
          name: '라이트 노벨',
          parent_id: '1',
          level: 3,
          route: '국내도서>소설/시/희곡>라이트 노벨',
          children: [
            {
              id: '51116',
              name: '기타 라이트노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>기타 라이트노벨',
              children: [],
            },
            {
              id: '88136',
              name: '나비노블(Nabi Novel)',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>나비노블(Nabi Novel)',
              children: [],
            },
            {
              id: '106545',
              name: '노블엔진 팝(pop)',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>노블엔진 팝(pop)',
              children: [],
            },
            {
              id: '54719',
              name: '노블엔진(Novel Engine)',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>노블엔진(Novel Engine)',
              children: [],
            },
            {
              id: '51080',
              name: '디-라이트(De-Light) 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>디-라이트(De-Light) 노벨',
              children: [],
            },
            {
              id: '162391',
              name: '라이트노벨 관련 상품',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>라이트노벨 관련 상품',
              children: [],
            },
            {
              id: '51107',
              name: '러쉬노벨 로맨스',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>러쉬노벨 로맨스',
              children: [],
            },
            {
              id: '121541',
              name: '레진 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>레진 노벨',
              children: [],
            },
            {
              id: '89171',
              name: '루트 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>루트 노벨',
              children: [],
            },
            {
              id: '112097',
              name: '메르헨 노블',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>메르헨 노블',
              children: [],
            },
            {
              id: '51083',
              name: '메이퀸(May-Queen) 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>메이퀸(May-Queen) 노벨',
              children: [],
            },
            {
              id: '114691',
              name: '소미미디어 문고',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>소미미디어 문고',
              children: [],
            },
            {
              id: '111196',
              name: '스위티노블',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>스위티노블',
              children: [],
            },
            {
              id: '110488',
              name: '스칼렛노블',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>스칼렛노블',
              children: [],
            },
            {
              id: '51071',
              name: '시드(Seed) 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>시드(Seed) 노벨',
              children: [],
            },
            {
              id: '51077',
              name: '아키-타입(Arche-type)',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>아키-타입(Arche-type)',
              children: [],
            },
            {
              id: '87919',
              name: '앨리스 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>앨리스 노벨',
              children: [],
            },
            {
              id: '128346',
              name: '에스큐브(SCUBE)',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>에스큐브(SCUBE)',
              children: [],
            },
            {
              id: '112098',
              name: '엘르 노블',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>엘르 노블',
              children: [],
            },
            {
              id: '51099',
              name: '윙크(Wink) 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>윙크(Wink) 노벨',
              children: [],
            },
            {
              id: '51102',
              name: '이슈(issue) 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>이슈(issue) 노벨',
              children: [],
            },
            {
              id: '51070',
              name: '익스트림(Extreme) 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>익스트림(Extreme) 노벨',
              children: [],
            },
            {
              id: '138767',
              name: '제이 노벨 넥스트(J Novel Next)',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>제이 노벨 넥스트(J Novel Next)',
              children: [],
            },
            {
              id: '51105',
              name: '제이(J) 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>제이(J) 노벨',
              children: [],
            },
            {
              id: '148769',
              name: '카니발 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>카니발 노벨',
              children: [],
            },
            {
              id: '148770',
              name: '카니발 플러스',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>카니발 플러스',
              children: [],
            },
            {
              id: '109725',
              name: '코르셋노블(Corset Novel)',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>코르셋노블(Corset Novel)',
              children: [],
            },
            {
              id: '89172',
              name: '파우스트 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>파우스트 노벨',
              children: [],
            },
            {
              id: '89168',
              name: '파우스트 박스',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>파우스트 박스',
              children: [],
            },
            {
              id: '154903',
              name: '폴라리스',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>폴라리스',
              children: [],
            },
            {
              id: '89166',
              name: 'AK 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>AK 노벨',
              children: [],
            },
            {
              id: '51114',
              name: 'B愛 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>B愛 노벨',
              children: [],
            },
            {
              id: '168549',
              name: 'JM 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>JM 노벨',
              children: [],
            },
            {
              id: '51106',
              name: 'L 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>L 노벨',
              children: [],
            },
            {
              id: '130122',
              name: 'L 북스',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>L 북스',
              children: [],
            },
            {
              id: '115694',
              name: 'MM 노블',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>MM 노블',
              children: [],
            },
            {
              id: '55624',
              name: 'NT library',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>NT library',
              children: [],
            },
            {
              id: '51069',
              name: 'NT(엔티) 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>NT(엔티) 노벨',
              children: [],
            },
            {
              id: '89167',
              name: 'S 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>S 노벨',
              children: [],
            },
            {
              id: '89169',
              name: 'V 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>V 노벨',
              children: [],
            },
            {
              id: '89170',
              name: 'Y 노벨',
              parent_id: '50927',
              level: 4,
              route: '국내도서>소설/시/희곡>라이트 노벨>Y 노벨',
              children: [],
            },
          ],
        },
        {
          id: '52650',
          name: '러시아소설',
          parent_id: '1',
          level: 3,
          route: '국내도서>소설/시/희곡>러시아소설',
          children: [],
        },
        {
          id: '50935',
          name: '로맨스소설',
          parent_id: '1',
          level: 3,
          route: '국내도서>소설/시/희곡>로맨스소설',
          children: [
            {
              id: '181723',
              name: '국내 BL',
              parent_id: '50935',
              level: 4,
              route: '국내도서>소설/시/희곡>로맨스소설>국내 BL',
              children: [],
            },
            {
              id: '181727',
              name: '국외 BL',
              parent_id: '50935',
              level: 4,
              route: '국내도서>소설/시/희곡>로맨스소설>국외 BL',
              children: [],
            },
            {
              id: '51126',
              name: '외국 로맨스소설',
              parent_id: '50935',
              level: 4,
              route: '국내도서>소설/시/희곡>로맨스소설>외국 로맨스소설',
              children: [],
            },
            {
              id: '51125',
              name: '한국 로맨스소설',
              parent_id: '50935',
              level: 4,
              route: '국내도서>소설/시/희곡>로맨스소설>한국 로맨스소설',
              children: [],
            },
          ],
        },
        {
          id: '50932',
          name: '무협소설',
          parent_id: '1',
          level: 3,
          route: '국내도서>소설/시/희곡>무협소설',
          children: [],
        },
        {
          id: '50951',
          name: '문학 잡지',
          parent_id: '1',
          level: 3,
          route: '국내도서>소설/시/희곡>문학 잡지',
          children: [
            {
              id: '51234',
              name: '기타',
              parent_id: '50951',
              level: 4,
              route: '국내도서>소설/시/희곡>문학 잡지>기타',
              children: [],
            },
            {
              id: '51218',
              name: '문학과사회',
              parent_id: '50951',
              level: 4,
              route: '국내도서>소설/시/희곡>문학 잡지>문학과사회',
              children: [],
            },
            {
              id: '51215',
              name: '문학동네',
              parent_id: '50951',
              level: 4,
              route: '국내도서>소설/시/희곡>문학 잡지>문학동네',
              children: [],
            },
            {
              id: '52653',
              name: '문학사상',
              parent_id: '50951',
              level: 4,
              route: '국내도서>소설/시/희곡>문학 잡지>문학사상',
              children: [],
            },
            {
              id: '51225',
              name: '세계의문학',
              parent_id: '50951',
              level: 4,
              route: '국내도서>소설/시/희곡>문학 잡지>세계의문학',
              children: [],
            },
            {
              id: '51230',
              name: '시평',
              parent_id: '50951',
              level: 4,
              route: '국내도서>소설/시/희곡>문학 잡지>시평',
              children: [],
            },
            {
              id: '51221',
              name: '실천문학',
              parent_id: '50951',
              level: 4,
              route: '국내도서>소설/시/희곡>문학 잡지>실천문학',
              children: [],
            },
            {
              id: '51229',
              name: '안과밖',
              parent_id: '50951',
              level: 4,
              route: '국내도서>소설/시/희곡>문학 잡지>안과밖',
              children: [],
            },
            {
              id: '157672',
              name: '언유주얼',
              parent_id: '50951',
              level: 4,
              route: '국내도서>소설/시/희곡>문학 잡지>언유주얼',
              children: [],
            },
            {
              id: '51223',
              name: '자음과모음',
              parent_id: '50951',
              level: 4,
              route: '국내도서>소설/시/희곡>문학 잡지>자음과모음',
              children: [],
            },
            {
              id: '51227',
              name: '작가세계',
              parent_id: '50951',
              level: 4,
              route: '국내도서>소설/시/희곡>문학 잡지>작가세계',
              children: [],
            },
            {
              id: '51213',
              name: '창작과비평',
              parent_id: '50951',
              level: 4,
              route: '국내도서>소설/시/희곡>문학 잡지>창작과비평',
              children: [],
            },
            {
              id: '51232',
              name: '판타스틱',
              parent_id: '50951',
              level: 4,
              route: '국내도서>소설/시/희곡>문학 잡지>판타스틱',
              children: [],
            },
            {
              id: '52654',
              name: '현대문학',
              parent_id: '50951',
              level: 4,
              route: '국내도서>소설/시/희곡>문학 잡지>현대문학',
              children: [],
            },
          ],
        },
        {
          id: '50945',
          name: '문학의 이해',
          parent_id: '1',
          level: 3,
          route: '국내도서>소설/시/희곡>문학의 이해',
          children: [
            {
              id: '51193',
              name: '문예사조',
              parent_id: '50945',
              level: 4,
              route: '국내도서>소설/시/희곡>문학의 이해>문예사조',
              children: [],
            },
            {
              id: '51179',
              name: '문학전문사전',
              parent_id: '50945',
              level: 4,
              route: '국내도서>소설/시/희곡>문학의 이해>문학전문사전',
              children: [],
            },
            {
              id: '51206',
              name: '비교문학론',
              parent_id: '50945',
              level: 4,
              route: '국내도서>소설/시/희곡>문학의 이해>비교문학론',
              children: [],
            },
            {
              id: '51191',
              name: '비평론',
              parent_id: '50945',
              level: 4,
              route: '국내도서>소설/시/희곡>문학의 이해>비평론',
              children: [],
            },
            {
              id: '51204',
              name: '세계문학론',
              parent_id: '50945',
              level: 4,
              route: '국내도서>소설/시/희곡>문학의 이해>세계문학론',
              children: [
                {
                  id: '51319',
                  name: '일본문학론',
                  parent_id: '51204',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>세계문학론>일본문학론',
                  children: [],
                },
                {
                  id: '51320',
                  name: '중국문학론',
                  parent_id: '51204',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>세계문학론>중국문학론',
                  children: [],
                },
                {
                  id: '51321',
                  name: '영미문학론',
                  parent_id: '51204',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>세계문학론>영미문학론',
                  children: [],
                },
                {
                  id: '51322',
                  name: '라틴문학론',
                  parent_id: '51204',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>세계문학론>라틴문학론',
                  children: [],
                },
                {
                  id: '51323',
                  name: '러시아문학론',
                  parent_id: '51204',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>세계문학론>러시아문학론',
                  children: [],
                },
                {
                  id: '51325',
                  name: '프랑스문학론',
                  parent_id: '51204',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>세계문학론>프랑스문학론',
                  children: [],
                },
                {
                  id: '51328',
                  name: '독일문학론',
                  parent_id: '51204',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>세계문학론>독일문학론',
                  children: [],
                },
                {
                  id: '51332',
                  name: '기타 세계문학론',
                  parent_id: '51204',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>세계문학론>기타 세계문학론',
                  children: [],
                },
              ],
            },
            {
              id: '51186',
              name: '소설론',
              parent_id: '50945',
              level: 4,
              route: '국내도서>소설/시/희곡>문학의 이해>소설론',
              children: [],
            },
            {
              id: '51190',
              name: '시론',
              parent_id: '50945',
              level: 4,
              route: '국내도서>소설/시/희곡>문학의 이해>시론',
              children: [],
            },
            {
              id: '51180',
              name: '우리말사전',
              parent_id: '50945',
              level: 4,
              route: '국내도서>소설/시/희곡>문학의 이해>우리말사전',
              children: [],
            },
            {
              id: '51196',
              name: '일반문학론',
              parent_id: '50945',
              level: 4,
              route: '국내도서>소설/시/희곡>문학의 이해>일반문학론',
              children: [],
            },
            {
              id: '51184',
              name: '작가론',
              parent_id: '50945',
              level: 4,
              route: '국내도서>소설/시/희곡>문학의 이해>작가론',
              children: [],
            },
            {
              id: '51182',
              name: '창작.문장작법',
              parent_id: '50945',
              level: 4,
              route: '국내도서>소설/시/희곡>문학의 이해>창작.문장작법',
              children: [],
            },
            {
              id: '51201',
              name: '한국문학론',
              parent_id: '50945',
              level: 4,
              route: '국내도서>소설/시/희곡>문학의 이해>한국문학론',
              children: [
                {
                  id: '51309',
                  name: '한국고전문학론',
                  parent_id: '51201',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>한국문학론>한국고전문학론',
                  children: [],
                },
                {
                  id: '51305',
                  name: '한국비평론',
                  parent_id: '51201',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>한국문학론>한국비평론',
                  children: [],
                },
                {
                  id: '51302',
                  name: '한국작가론',
                  parent_id: '51201',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>한국문학론>한국작가론',
                  children: [],
                },
                {
                  id: '51303',
                  name: '한국희곡론',
                  parent_id: '51201',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>한국문학론>한국희곡론',
                  children: [],
                },
                {
                  id: '51300',
                  name: '한국시론',
                  parent_id: '51201',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>한국문학론>한국시론',
                  children: [],
                },
                {
                  id: '51297',
                  name: '한국소설론',
                  parent_id: '51201',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>한국문학론>한국소설론',
                  children: [],
                },
                {
                  id: '51295',
                  name: '한국문학사',
                  parent_id: '51201',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>한국문학론>한국문학사',
                  children: [],
                },
                {
                  id: '51316',
                  name: '북한문학론',
                  parent_id: '51201',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>한국문학론>북한문학론',
                  children: [],
                },
                {
                  id: '51313',
                  name: '주제평론',
                  parent_id: '51201',
                  level: 5,
                  route: '국내도서>소설/시/희곡>문학의 이해>한국문학론>주제평론',
                  children: [],
                },
              ],
            },
            {
              id: '51198',
              name: '한글이야기',
              parent_id: '50945',
              level: 4,
              route: '국내도서>소설/시/희곡>문학의 이해>한글이야기',
              children: [],
            },
          ],
        },
      ],
    },
  ];
  const transformData = (data: Category[]): any[] =>
    data.map((item: Category) => ({
      title: item.name,
      key: item.id,
      children: item.children ? transformData(item.children) : [],
      route: item.route,
      level: item.level,
    }));

  const catLevel2 = categories.filter((category) => category.level === 2);
  const treeData = transformData(catLevel2);

  console.log('RESPONSE: ', treeData);
  return (
    <div className="bg-green-200">
      <h1 className="text-xl text-white">Welcome to BookDo7Stars!!!!!!</h1>
      <Tree treeData={treeData} showIcon={false} defaultExpandAll={false} selectable onSelect={(selectedKeys) => console.log('Selected:', selectedKeys)} />
    </div>
  );
}
